#!/usr/bin/env bash
#Displays best school 10 times but for the 9th iteration dsiplays best school 
COUNT=9
while((COUNT>=0));do
	echo "Best School"
	if [ "$COUNT" -eq 1 ] ;then
		echo "Hi"
	fi
	((COUNT--))
done;
