#!/usr/bin/env bash
#Displays best school 10 times but for the 9th iteration dsiplays best school and then hi on a new line
COUNT=9
while((Count>=0));
do
   echo "Best School"
if ["$COUNT" -eq 1] ;then
echo "Hi"
fi
((COUNT--))
done; 
