#!/usr/bin/env bash
#Script that loops from 1 to 10
COUNT=0
while((COUNT<10));do
	if [ "$COUNT" -eq 7 ] ;then
		echo "good luck"
	elif [ "$COUNT -eq 3 ] ;then
		echo "bad luck"
	else
		echo "Best School"
	fi
	((COUNT++))
done;
