#!/usr/bin/env bash
#Superstitious numbers
COUNT=1
while ((COUNT<=20));do
    echo "$COUNT"
case $COUNT in
   4) echo "bad luckfrom china"
       ;;
   9) echo "bad luck from Japan"
       ;;
  17) echo "bad luck from Italy"
       ;;
     esac
((COUNT++))
done;
