#!/usr/bin/env bash
#Displays the time for 12 hours and 59 minutes
COUNT=0
while((COUNT<=12))0;do
	echo "Hour: $COUNT"
	HOUR=1
	While((HOUR<=59));do
	echo "$HOUR"
	((HOUR++))
done;
((COUNT++))
done;

